name: CI Feature

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'
      - '!master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./configs/docker/prod.dockerfile
          load: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/employees-fe:latest
      -
        name: Inspect
        run: |
          docker image inspect ${{ secrets.DOCKER_HUB_USERNAME }}/employees-fe:latest
