name: CI Feature

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'
      - '!master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       -
        name: Checkout
        uses: actions/checkout@v2
